import Head from "next/head";

// Saas UI & Chakra UI Imports
import { AppShell } from "@saas-ui/react";
import { Box, Tabs, TabList, TabPanels, Tab, TabPanel } from "@chakra-ui/react";

// My Components
import { UserSettings } from "./usersettings.jsx";
import { MySidebar } from "./MySidebar.jsx";

export default function Home() {
  return (
    <section className="banner_area profile">
      <div className="booking_table d_flex align-items-center">
        <div
          className="overlay bg-parallax"
          data-stellar-ratio="0.9"
          data-stellar-vertical-offset="0"
          data-background=""
        ></div>

        <div className="container">
          <Head>
            <title>MySaaS &gt; Account Settings</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <AppShell sidebar={<MySidebar />}>
            <Box h="100%" w="100%" padding="1em">
              <Tabs isFitted size="md" variant="enclosed">
                <TabList>
                  <Tab _selected={{ color: "white", bg: "primary.500" }}>
                    User
                  </Tab>
                  <Tab _selected={{ color: "white", bg: "primary.500" }}>
                    Integrations
                  </Tab>
                  <Tab _selected={{ color: "white", bg: "primary.500" }}>
                    Security
                  </Tab>
                  <Tab _selected={{ color: "white", bg: "primary.500" }}>
                    Billing
                  </Tab>
                </TabList>
                <TabPanels>
                  <TabPanel>
                    <UserSettings />
                  </TabPanel>
                  <TabPanel>
                    <p>Integrations Here!</p>
                  </TabPanel>
                  <TabPanel>
                    <p>Security Here!</p>
                  </TabPanel>
                  <TabPanel>
                    <p>Billing Here!</p>
                  </TabPanel>
                </TabPanels>
              </Tabs>
            </Box>
          </AppShell>
        </div>
      </div>
    </section>
  );
}
